# Generated by Django 5.1.5 on 2025-01-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogger',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
