# Generated by Django 5.1.5 on 2025-01-18 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylogger', '0003_remove_timelogger_activity_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelogger',
            name='activities',
        ),
        migrations.AddField(
            model_name='timelogger',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activitylogger.activity'),
        ),
    ]
