# Generated by Django 5.1.5 on 2025-01-18 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylogger', '0004_remove_timelogger_activities_timelogger_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogger',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activitylogger.activity'),
        ),
    ]
