# Generated by Django 5.1.5 on 2025-01-18 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylogger', '0005_alter_timelogger_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogger',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activitylogger.activity'),
        ),
    ]
