# Generated by Django 5.1.5 on 2025-01-20 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_muscle', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_muscle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_time', models.DurationField(default='00:00:00', help_text='Rest time (HH:MM:SS)')),
                ('order', models.PositiveIntegerField(default=1)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymtracker.exercise')),
            ],
            options={
                'verbose_name': 'Routine Exercise',
                'verbose_name_plural': 'Routine Exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('unidad_peso', models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras')], default='kg', max_length=2)),
                ('repeticiones', models.PositiveIntegerField()),
                ('numero_serie', models.PositiveIntegerField()),
                ('ejercicio_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie', to='gymtracker.exerciseworkout')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ejercicios', models.ManyToManyField(through='gymtracker.ExerciseWorkout', to='gymtracker.exercise')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exerciseworkout',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymtracker.workout'),
        ),
    ]
