# Generated by Django 5.1.4 on 2024-12-31 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('grupo_muscular', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='set',
            name='workout_exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.CreateModel(
            name='EjercicioRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('ejercicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymtracker.ejercicios')),
            ],
        ),
        migrations.CreateModel(
            name='Rutinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ejercicios', models.ManyToManyField(through='gymtracker.EjercicioRutina', to='gymtracker.ejercicios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ejerciciorutina',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymtracker.rutinas'),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('unidad_peso', models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras')], default='kg', max_length=2)),
                ('repeticiones', models.PositiveIntegerField()),
                ('numero_serie', models.PositiveIntegerField()),
                ('tiempo_descanso', models.DurationField()),
                ('ejercicio_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie', to='gymtracker.ejerciciorutina')),
            ],
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
