# Generated by Django 5.1.5 on 2025-01-30 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100, verbose_name='Nombre del ejercicio')),
                ('rest_time', models.DurationField(verbose_name='Tiempo de descanso')),
                ('order', models.PositiveIntegerField(verbose_name='Orden en la rutina')),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=2, verbose_name='Unidad de peso')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymtracker.exercise', verbose_name='Ejercicio original')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LoggedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('repetitions', models.PositiveIntegerField(verbose_name='Repeticiones')),
                ('set_number', models.PositiveIntegerField(verbose_name='Número de serie')),
                ('logged_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_sets', to='gymtracker.loggedexercise')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='LoggedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('original_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymtracker.workout', verbose_name='Rutina original')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loggedexercise',
            name='logged_workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_exercises', to='gymtracker.loggedworkout'),
        ),
    ]
