# Generated by Django 5.1.5 on 2025-01-20 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseworkout',
            options={'ordering': ['order'], 'verbose_name': 'Workout Exercise', 'verbose_name_plural': 'Workout Exercises'},
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='ejercicios',
            new_name='exercises',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='exerciseworkout',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order of the exercise in the workout'),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Weight used in this set')),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=2)),
                ('repetitions', models.PositiveIntegerField(help_text='Number of repetitions in this set')),
                ('set_number', models.PositiveIntegerField(help_text='Set number (e.g., 1, 2, 3)')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='gymtracker.exerciseworkout')),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Sets',
                'ordering': ['set_number'],
            },
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
