# Generated by Django 5.1.5 on 2025-01-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='weight_unit',
        ),
        migrations.AddField(
            model_name='exerciseworkout',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=2),
        ),
    ]
