# Generated by Django 5.1.4 on 2025-01-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0002_ejercicios_remove_workoutexercise_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicios',
            name='ruta_imagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
