# Generated by Django 5.1.5 on 2025-01-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0002_alter_exerciseworkout_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
