# Generated by Django 5.1.4 on 2025-01-02 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0003_ejercicios_ruta_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ejercicios',
            new_name='Ejercicio',
        ),
        migrations.RenameModel(
            old_name='Rutinas',
            new_name='Rutina',
        ),
        migrations.AlterModelOptions(
            name='ejerciciorutina',
            options={'verbose_name': 'Ejercicio Rutina', 'verbose_name_plural': 'Ejercicios Rutinas'},
        ),
    ]
