# Generated by Django 5.1.4 on 2025-01-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0004_rename_ejercicios_ejercicio_rename_rutinas_rutina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='grupo_muscular',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='primary_muscle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='secondary_muscle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
