# Generated by Django 5.1.4 on 2025-01-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goaltracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
