# Generated by Django 5.1.4 on 2025-01-05 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goaltracker', '0003_objective_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='goaltracker.goal'),
        ),
    ]
